# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from policy.unsafe import unsafe_pb2 as policy_dot_unsafe_dot_unsafe__pb2


class UnsafeServiceStub(object):
    """/
    / Unsafe Service
    /
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnsafeUpdateNamespace = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeUpdateNamespace',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceResponse.FromString,
                _registered_method=True)
        self.UnsafeReactivateNamespace = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeReactivateNamespace',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceResponse.FromString,
                _registered_method=True)
        self.UnsafeDeleteNamespace = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeDeleteNamespace',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceResponse.FromString,
                _registered_method=True)
        self.UnsafeUpdateAttribute = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeUpdateAttribute',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeResponse.FromString,
                _registered_method=True)
        self.UnsafeReactivateAttribute = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeReactivateAttribute',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeResponse.FromString,
                _registered_method=True)
        self.UnsafeDeleteAttribute = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeDeleteAttribute',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeResponse.FromString,
                _registered_method=True)
        self.UnsafeUpdateAttributeValue = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeUpdateAttributeValue',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueResponse.FromString,
                _registered_method=True)
        self.UnsafeReactivateAttributeValue = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeReactivateAttributeValue',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueResponse.FromString,
                _registered_method=True)
        self.UnsafeDeleteAttributeValue = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeDeleteAttributeValue',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueResponse.FromString,
                _registered_method=True)
        self.UnsafeDeleteKasKey = channel.unary_unary(
                '/policy.unsafe.UnsafeService/UnsafeDeleteKasKey',
                request_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyRequest.SerializeToString,
                response_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyResponse.FromString,
                _registered_method=True)


class UnsafeServiceServicer(object):
    """/
    / Unsafe Service
    /
    """

    def UnsafeUpdateNamespace(self, request, context):
        """--------------------------------------*
        Namespace RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeReactivateNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeDeleteNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeUpdateAttribute(self, request, context):
        """--------------------------------------*
        Attribute RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeReactivateAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeDeleteAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeUpdateAttributeValue(self, request, context):
        """--------------------------------------*
        Value RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeReactivateAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeDeleteAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsafeDeleteKasKey(self, request, context):
        """--------------------------------------*
        Kas Key RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnsafeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnsafeUpdateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeUpdateNamespace,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceResponse.SerializeToString,
            ),
            'UnsafeReactivateNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeReactivateNamespace,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceResponse.SerializeToString,
            ),
            'UnsafeDeleteNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeDeleteNamespace,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceResponse.SerializeToString,
            ),
            'UnsafeUpdateAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeUpdateAttribute,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeResponse.SerializeToString,
            ),
            'UnsafeReactivateAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeReactivateAttribute,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeResponse.SerializeToString,
            ),
            'UnsafeDeleteAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeDeleteAttribute,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeResponse.SerializeToString,
            ),
            'UnsafeUpdateAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeUpdateAttributeValue,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueResponse.SerializeToString,
            ),
            'UnsafeReactivateAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeReactivateAttributeValue,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueResponse.SerializeToString,
            ),
            'UnsafeDeleteAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeDeleteAttributeValue,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueResponse.SerializeToString,
            ),
            'UnsafeDeleteKasKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsafeDeleteKasKey,
                    request_deserializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyRequest.FromString,
                    response_serializer=policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy.unsafe.UnsafeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy.unsafe.UnsafeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UnsafeService(object):
    """/
    / Unsafe Service
    /
    """

    @staticmethod
    def UnsafeUpdateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeUpdateNamespace',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeReactivateNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeReactivateNamespace',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeDeleteNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeDeleteNamespace',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeUpdateAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeUpdateAttribute',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeReactivateAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeReactivateAttribute',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeDeleteAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeDeleteAttribute',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeUpdateAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeUpdateAttributeValue',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeUpdateAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeReactivateAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeReactivateAttributeValue',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeReactivateAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeDeleteAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeDeleteAttributeValue',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsafeDeleteKasKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.unsafe.UnsafeService/UnsafeDeleteKasKey',
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyRequest.SerializeToString,
            policy_dot_unsafe_dot_unsafe__pb2.UnsafeDeleteKasKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
