version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/packages/otdf-python"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/packages/otdf-python-proto"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
