# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: policy/subjectmapping/subject_mapping.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import policy.subjectmapping.subject_mapping_pb2 as policy_dot_subjectmapping_dot_subject__mapping__pb2


class SubjectMappingService(Protocol):
    async def match_subject_mappings(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_subject_mappings(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_subject_condition_sets(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_all_unmapped_subject_condition_sets(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SubjectMappingServiceASGIApplication(ConnectASGIApplication[SubjectMappingService]):
    def __init__(self, service: SubjectMappingService | AsyncGenerator[SubjectMappingService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/policy.subjectmapping.SubjectMappingService/MatchSubjectMappings": Endpoint.unary(
                    method=MethodInfo(
                        name="MatchSubjectMappings",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.match_subject_mappings,
                ),
                "/policy.subjectmapping.SubjectMappingService/ListSubjectMappings": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSubjectMappings",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_subject_mappings,
                ),
                "/policy.subjectmapping.SubjectMappingService/GetSubjectMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/CreateSubjectMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/UpdateSubjectMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteSubjectMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/ListSubjectConditionSets": Endpoint.unary(
                    method=MethodInfo(
                        name="ListSubjectConditionSets",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_subject_condition_sets,
                ),
                "/policy.subjectmapping.SubjectMappingService/GetSubjectConditionSet": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/CreateSubjectConditionSet": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/UpdateSubjectConditionSet": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteSubjectConditionSet": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteAllUnmappedSubjectConditionSets": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAllUnmappedSubjectConditionSets",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_all_unmapped_subject_condition_sets,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.subjectmapping.SubjectMappingService"


class SubjectMappingServiceClient(ConnectClient):
    async def match_subject_mappings(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MatchSubjectMappings",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_subject_mappings(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubjectMappings",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_subject_condition_sets(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubjectConditionSets",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_all_unmapped_subject_condition_sets(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllUnmappedSubjectConditionSets",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class SubjectMappingServiceSync(Protocol):
    def match_subject_mappings(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_subject_mappings(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_subject_mapping(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_subject_condition_sets(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_subject_condition_set(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_all_unmapped_subject_condition_sets(self, request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest, ctx: RequestContext) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SubjectMappingServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SubjectMappingServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/policy.subjectmapping.SubjectMappingService/MatchSubjectMappings": EndpointSync.unary(
                    method=MethodInfo(
                        name="MatchSubjectMappings",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.match_subject_mappings,
                ),
                "/policy.subjectmapping.SubjectMappingService/ListSubjectMappings": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSubjectMappings",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_subject_mappings,
                ),
                "/policy.subjectmapping.SubjectMappingService/GetSubjectMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/CreateSubjectMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/UpdateSubjectMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteSubjectMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSubjectMapping",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_subject_mapping,
                ),
                "/policy.subjectmapping.SubjectMappingService/ListSubjectConditionSets": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListSubjectConditionSets",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_subject_condition_sets,
                ),
                "/policy.subjectmapping.SubjectMappingService/GetSubjectConditionSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/CreateSubjectConditionSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/UpdateSubjectConditionSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteSubjectConditionSet": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSubjectConditionSet",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_subject_condition_set,
                ),
                "/policy.subjectmapping.SubjectMappingService/DeleteAllUnmappedSubjectConditionSets": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAllUnmappedSubjectConditionSets",
                        service_name="policy.subjectmapping.SubjectMappingService",
                        input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
                        output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_all_unmapped_subject_condition_sets,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.subjectmapping.SubjectMappingService"


class SubjectMappingServiceClientSync(ConnectClientSync):
    def match_subject_mappings(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MatchSubjectMappings",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.MatchSubjectMappingsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_subject_mappings(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubjectMappings",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectMappingsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_subject_mapping(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubjectMapping",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_subject_condition_sets(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListSubjectConditionSets",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.ListSubjectConditionSetsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.GetSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.CreateSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.UpdateSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_subject_condition_set(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSubjectConditionSet",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteSubjectConditionSetResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_all_unmapped_subject_condition_sets(
        self,
        request: policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAllUnmappedSubjectConditionSets",
                service_name="policy.subjectmapping.SubjectMappingService",
                input=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsRequest,
                output=policy_dot_subjectmapping_dot_subject__mapping__pb2.DeleteAllUnmappedSubjectConditionSetsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
