# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: policy/resourcemapping/resource_mapping.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import policy.resourcemapping.resource_mapping_pb2 as policy_dot_resourcemapping_dot_resource__mapping__pb2


class ResourceMappingService(Protocol):
    async def list_resource_mapping_groups(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_resource_mappings(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_resource_mappings_by_group_fqns(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ResourceMappingServiceASGIApplication(ConnectASGIApplication[ResourceMappingService]):
    def __init__(self, service: ResourceMappingService | AsyncGenerator[ResourceMappingService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappingGroups": Endpoint.unary(
                    method=MethodInfo(
                        name="ListResourceMappingGroups",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_resource_mapping_groups,
                ),
                "/policy.resourcemapping.ResourceMappingService/GetResourceMappingGroup": Endpoint.unary(
                    method=MethodInfo(
                        name="GetResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/CreateResourceMappingGroup": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/UpdateResourceMappingGroup": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/DeleteResourceMappingGroup": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappings": Endpoint.unary(
                    method=MethodInfo(
                        name="ListResourceMappings",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_resource_mappings,
                ),
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappingsByGroupFqns": Endpoint.unary(
                    method=MethodInfo(
                        name="ListResourceMappingsByGroupFqns",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_resource_mappings_by_group_fqns,
                ),
                "/policy.resourcemapping.ResourceMappingService/GetResourceMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="GetResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/CreateResourceMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/UpdateResourceMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/DeleteResourceMapping": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_resource_mapping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.resourcemapping.ResourceMappingService"


class ResourceMappingServiceClient(ConnectClient):
    async def list_resource_mapping_groups(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappingGroups",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_resource_mappings(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappings",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_resource_mappings_by_group_fqns(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappingsByGroupFqns",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ResourceMappingServiceSync(Protocol):
    def list_resource_mapping_groups(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_resource_mapping_group(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_resource_mappings(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_resource_mappings_by_group_fqns(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_resource_mapping(self, request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest, ctx: RequestContext) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ResourceMappingServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ResourceMappingServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappingGroups": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListResourceMappingGroups",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_resource_mapping_groups,
                ),
                "/policy.resourcemapping.ResourceMappingService/GetResourceMappingGroup": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/CreateResourceMappingGroup": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/UpdateResourceMappingGroup": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/DeleteResourceMappingGroup": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteResourceMappingGroup",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_resource_mapping_group,
                ),
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappings": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListResourceMappings",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_resource_mappings,
                ),
                "/policy.resourcemapping.ResourceMappingService/ListResourceMappingsByGroupFqns": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListResourceMappingsByGroupFqns",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_resource_mappings_by_group_fqns,
                ),
                "/policy.resourcemapping.ResourceMappingService/GetResourceMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/CreateResourceMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/UpdateResourceMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_resource_mapping,
                ),
                "/policy.resourcemapping.ResourceMappingService/DeleteResourceMapping": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteResourceMapping",
                        service_name="policy.resourcemapping.ResourceMappingService",
                        input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
                        output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_resource_mapping,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.resourcemapping.ResourceMappingService"


class ResourceMappingServiceClientSync(ConnectClientSync):
    def list_resource_mapping_groups(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappingGroups",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingGroupsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_resource_mapping_group(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResourceMappingGroup",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingGroupResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_resource_mappings(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappings",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def list_resource_mappings_by_group_fqns(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListResourceMappingsByGroupFqns",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.ListResourceMappingsByGroupFqnsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.GetResourceMappingResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.CreateResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.UpdateResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_resource_mapping(
        self,
        request: policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteResourceMapping",
                service_name="policy.resourcemapping.ResourceMappingService",
                input=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingRequest,
                output=policy_dot_resourcemapping_dot_resource__mapping__pb2.DeleteResourceMappingResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
