# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: policy/keymanagement/key_management.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import policy.keymanagement.key_management_pb2 as policy_dot_keymanagement_dot_key__management__pb2


class KeyManagementService(Protocol):
    async def create_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_provider_configs(self, request: policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KeyManagementServiceASGIApplication(ConnectASGIApplication[KeyManagementService]):
    def __init__(self, service: KeyManagementService | AsyncGenerator[KeyManagementService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/policy.keymanagement.KeyManagementService/CreateProviderConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/GetProviderConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/ListProviderConfigs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProviderConfigs",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_provider_configs,
                ),
                "/policy.keymanagement.KeyManagementService/UpdateProviderConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/DeleteProviderConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_provider_config,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.keymanagement.KeyManagementService"


class KeyManagementServiceClient(ConnectClient):
    async def create_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_provider_configs(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviderConfigs",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class KeyManagementServiceSync(Protocol):
    def create_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_provider_configs(self, request: policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_provider_config(self, request: policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest, ctx: RequestContext) -> policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KeyManagementServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: KeyManagementServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/policy.keymanagement.KeyManagementService/CreateProviderConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/GetProviderConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/ListProviderConfigs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProviderConfigs",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_provider_configs,
                ),
                "/policy.keymanagement.KeyManagementService/UpdateProviderConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_provider_config,
                ),
                "/policy.keymanagement.KeyManagementService/DeleteProviderConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteProviderConfig",
                        service_name="policy.keymanagement.KeyManagementService",
                        input=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
                        output=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_provider_config,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.keymanagement.KeyManagementService"


class KeyManagementServiceClientSync(ConnectClientSync):
    def create_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.CreateProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.GetProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_provider_configs(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviderConfigs",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.ListProviderConfigsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.UpdateProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_provider_config(
        self,
        request: policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProviderConfig",
                service_name="policy.keymanagement.KeyManagementService",
                input=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigRequest,
                output=policy_dot_keymanagement_dot_key__management__pb2.DeleteProviderConfigResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
