# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger/audit/test.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logger/audit/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17logger/audit/test.proto\x12\x14service.logger.audit\x1a\x13\x63ommon/common.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc4\x02\n\x10TestPolicyObject\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x32\n\x06\x61\x63tive\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValueR\x06\x61\x63tive\x12K\n\x07version\x18\x03 \x01(\x0e\x32\x31.service.logger.audit.TestPolicyObjectVersionEnumR\x07version\x12\x12\n\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n\x08username\x18\x06 \x01(\tH\x00R\x08username\x12\x30\n\x04user\x18\x07 \x01(\x0b\x32\x1a.service.logger.audit.UserH\x00R\x04user\x12,\n\x08metadata\x18\x04 \x01(\x0b\x32\x10.common.MetadataR\x08metadataB\r\n\x0bpolicy_user\"*\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name*\xa0\x01\n\x1bTestPolicyObjectVersionEnum\x12/\n+TEST_POLICY_OBJECT_VERSION_ENUM_UNSPECIFIED\x10\x00\x12\'\n#TEST_POLICY_OBJECT_VERSION_ENUM_OLD\x10\x01\x12\'\n#TEST_POLICY_OBJECT_VERSION_ENUM_NEW\x10\x02\x42\x97\x01\n\x18\x63om.service.logger.auditB\tTestProtoP\x01\xa2\x02\x03SLA\xaa\x02\x14Service.Logger.Audit\xca\x02\x14Service\\Logger\\Audit\xe2\x02 Service\\Logger\\Audit\\GPBMetadata\xea\x02\x16Service::Logger::Auditb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger.audit.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.service.logger.auditB\tTestProtoP\001\242\002\003SLA\252\002\024Service.Logger.Audit\312\002\024Service\\Logger\\Audit\342\002 Service\\Logger\\Audit\\GPBMetadata\352\002\026Service::Logger::Audit'
  _globals['_TESTPOLICYOBJECTVERSIONENUM']._serialized_start=474
  _globals['_TESTPOLICYOBJECTVERSIONENUM']._serialized_end=634
  _globals['_TESTPOLICYOBJECT']._serialized_start=103
  _globals['_TESTPOLICYOBJECT']._serialized_end=427
  _globals['_USER']._serialized_start=429
  _globals['_USER']._serialized_end=471
# @@protoc_insertion_point(module_scope)
