# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from policy.attributes import attributes_pb2 as policy_dot_attributes_dot_attributes__pb2


class AttributesServiceStub(object):
    """/
    / Attribute Service
    /
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAttributes = channel.unary_unary(
                '/policy.attributes.AttributesService/ListAttributes',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.ListAttributesRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.ListAttributesResponse.FromString,
                _registered_method=True)
        self.ListAttributeValues = channel.unary_unary(
                '/policy.attributes.AttributesService/ListAttributeValues',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesResponse.FromString,
                _registered_method=True)
        self.GetAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/GetAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeResponse.FromString,
                _registered_method=True)
        self.GetAttributeValuesByFqns = channel.unary_unary(
                '/policy.attributes.AttributesService/GetAttributeValuesByFqns',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsResponse.FromString,
                _registered_method=True)
        self.CreateAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/CreateAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeResponse.FromString,
                _registered_method=True)
        self.UpdateAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/UpdateAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeResponse.FromString,
                _registered_method=True)
        self.DeactivateAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/DeactivateAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeResponse.FromString,
                _registered_method=True)
        self.GetAttributeValue = channel.unary_unary(
                '/policy.attributes.AttributesService/GetAttributeValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValueResponse.FromString,
                _registered_method=True)
        self.CreateAttributeValue = channel.unary_unary(
                '/policy.attributes.AttributesService/CreateAttributeValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueResponse.FromString,
                _registered_method=True)
        self.UpdateAttributeValue = channel.unary_unary(
                '/policy.attributes.AttributesService/UpdateAttributeValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueResponse.FromString,
                _registered_method=True)
        self.DeactivateAttributeValue = channel.unary_unary(
                '/policy.attributes.AttributesService/DeactivateAttributeValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueResponse.FromString,
                _registered_method=True)
        self.AssignKeyAccessServerToAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/AssignKeyAccessServerToAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeResponse.FromString,
                _registered_method=True)
        self.RemoveKeyAccessServerFromAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/RemoveKeyAccessServerFromAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeResponse.FromString,
                _registered_method=True)
        self.AssignKeyAccessServerToValue = channel.unary_unary(
                '/policy.attributes.AttributesService/AssignKeyAccessServerToValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueResponse.FromString,
                _registered_method=True)
        self.RemoveKeyAccessServerFromValue = channel.unary_unary(
                '/policy.attributes.AttributesService/RemoveKeyAccessServerFromValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueResponse.FromString,
                _registered_method=True)
        self.AssignPublicKeyToAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/AssignPublicKeyToAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeResponse.FromString,
                _registered_method=True)
        self.RemovePublicKeyFromAttribute = channel.unary_unary(
                '/policy.attributes.AttributesService/RemovePublicKeyFromAttribute',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeResponse.FromString,
                _registered_method=True)
        self.AssignPublicKeyToValue = channel.unary_unary(
                '/policy.attributes.AttributesService/AssignPublicKeyToValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueResponse.FromString,
                _registered_method=True)
        self.RemovePublicKeyFromValue = channel.unary_unary(
                '/policy.attributes.AttributesService/RemovePublicKeyFromValue',
                request_serializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueRequest.SerializeToString,
                response_deserializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueResponse.FromString,
                _registered_method=True)


class AttributesServiceServicer(object):
    """/
    / Attribute Service
    /
    """

    def ListAttributes(self, request, context):
        """--------------------------------------*
        Attribute RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAttributeValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeValuesByFqns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeValue(self, request, context):
        """--------------------------------------*
        Value RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignKeyAccessServerToAttribute(self, request, context):
        """--------------------------------------*
        Attribute <> Key Access Server RPCs
        ---------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveKeyAccessServerFromAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignKeyAccessServerToValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveKeyAccessServerFromValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignPublicKeyToAttribute(self, request, context):
        """--------------------------------------*
        Attribute <> Key RPCs
        ---------------------------------------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePublicKeyFromAttribute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignPublicKeyToValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePublicKeyFromValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAttributes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAttributes,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.ListAttributesRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.ListAttributesResponse.SerializeToString,
            ),
            'ListAttributeValues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAttributeValues,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesResponse.SerializeToString,
            ),
            'GetAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeResponse.SerializeToString,
            ),
            'GetAttributeValuesByFqns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeValuesByFqns,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsResponse.SerializeToString,
            ),
            'CreateAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeResponse.SerializeToString,
            ),
            'UpdateAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeResponse.SerializeToString,
            ),
            'DeactivateAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeResponse.SerializeToString,
            ),
            'GetAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.GetAttributeValueResponse.SerializeToString,
            ),
            'CreateAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAttributeValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueResponse.SerializeToString,
            ),
            'UpdateAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAttributeValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueResponse.SerializeToString,
            ),
            'DeactivateAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateAttributeValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueResponse.SerializeToString,
            ),
            'AssignKeyAccessServerToAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignKeyAccessServerToAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeResponse.SerializeToString,
            ),
            'RemoveKeyAccessServerFromAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveKeyAccessServerFromAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeResponse.SerializeToString,
            ),
            'AssignKeyAccessServerToValue': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignKeyAccessServerToValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueResponse.SerializeToString,
            ),
            'RemoveKeyAccessServerFromValue': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveKeyAccessServerFromValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueResponse.SerializeToString,
            ),
            'AssignPublicKeyToAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignPublicKeyToAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeResponse.SerializeToString,
            ),
            'RemovePublicKeyFromAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePublicKeyFromAttribute,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeResponse.SerializeToString,
            ),
            'AssignPublicKeyToValue': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignPublicKeyToValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueResponse.SerializeToString,
            ),
            'RemovePublicKeyFromValue': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePublicKeyFromValue,
                    request_deserializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueRequest.FromString,
                    response_serializer=policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy.attributes.AttributesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy.attributes.AttributesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttributesService(object):
    """/
    / Attribute Service
    /
    """

    @staticmethod
    def ListAttributes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/ListAttributes',
            policy_dot_attributes_dot_attributes__pb2.ListAttributesRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.ListAttributesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAttributeValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/ListAttributeValues',
            policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.ListAttributeValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/GetAttribute',
            policy_dot_attributes_dot_attributes__pb2.GetAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.GetAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributeValuesByFqns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/GetAttributeValuesByFqns',
            policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.GetAttributeValuesByFqnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/CreateAttribute',
            policy_dot_attributes_dot_attributes__pb2.CreateAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.CreateAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/UpdateAttribute',
            policy_dot_attributes_dot_attributes__pb2.UpdateAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.UpdateAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/DeactivateAttribute',
            policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/GetAttributeValue',
            policy_dot_attributes_dot_attributes__pb2.GetAttributeValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.GetAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/CreateAttributeValue',
            policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.CreateAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/UpdateAttributeValue',
            policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.UpdateAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/DeactivateAttributeValue',
            policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.DeactivateAttributeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignKeyAccessServerToAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/AssignKeyAccessServerToAttribute',
            policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveKeyAccessServerFromAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/RemoveKeyAccessServerFromAttribute',
            policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignKeyAccessServerToValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/AssignKeyAccessServerToValue',
            policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.AssignKeyAccessServerToValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveKeyAccessServerFromValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/RemoveKeyAccessServerFromValue',
            policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.RemoveKeyAccessServerFromValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignPublicKeyToAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/AssignPublicKeyToAttribute',
            policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePublicKeyFromAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/RemovePublicKeyFromAttribute',
            policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromAttributeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignPublicKeyToValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/AssignPublicKeyToValue',
            policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.AssignPublicKeyToValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePublicKeyFromValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.attributes.AttributesService/RemovePublicKeyFromValue',
            policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueRequest.SerializeToString,
            policy_dot_attributes_dot_attributes__pb2.RemovePublicKeyFromValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
