# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: policy/kasregistry/key_access_server_registry.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import policy.kasregistry.key_access_server_registry_pb2 as policy_dot_kasregistry_dot_key__access__server__registry__pb2


class KeyAccessServerRegistryService(Protocol):
    async def list_key_access_servers(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_key_access_server_grants(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_keys(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def rotate_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def set_base_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_base_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KeyAccessServerRegistryServiceASGIApplication(ConnectASGIApplication[KeyAccessServerRegistryService]):
    def __init__(self, service: KeyAccessServerRegistryService | AsyncGenerator[KeyAccessServerRegistryService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListKeyAccessServers",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_key_access_servers,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetKeyAccessServer": Endpoint.unary(
                    method=MethodInfo(
                        name="GetKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/CreateKeyAccessServer": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKeyAccessServer": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/DeleteKeyAccessServer": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServerGrants": Endpoint.unary(
                    method=MethodInfo(
                        name="ListKeyAccessServerGrants",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_key_access_server_grants,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/CreateKey": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetKey": Endpoint.unary(
                    method=MethodInfo(
                        name="GetKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeys": Endpoint.unary(
                    method=MethodInfo(
                        name="ListKeys",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_keys,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKey": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/RotateKey": Endpoint.unary(
                    method=MethodInfo(
                        name="RotateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.rotate_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/SetBaseKey": Endpoint.unary(
                    method=MethodInfo(
                        name="SetBaseKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.set_base_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetBaseKey": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBaseKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_base_key,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.kasregistry.KeyAccessServerRegistryService"


class KeyAccessServerRegistryServiceClient(ConnectClient):
    async def list_key_access_servers(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeyAccessServers",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_key_access_server_grants(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeyAccessServerGrants",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_keys(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeys",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def rotate_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_base_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetBaseKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_base_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBaseKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class KeyAccessServerRegistryServiceSync(Protocol):
    def list_key_access_servers(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_key_access_server(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_key_access_server_grants(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_keys(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def rotate_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def set_base_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_base_key(self, request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest, ctx: RequestContext) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class KeyAccessServerRegistryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: KeyAccessServerRegistryServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListKeyAccessServers",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_key_access_servers,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetKeyAccessServer": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/CreateKeyAccessServer": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKeyAccessServer": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/DeleteKeyAccessServer": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteKeyAccessServer",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_key_access_server,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServerGrants": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListKeyAccessServerGrants",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_key_access_server_grants,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/CreateKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/ListKeys": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListKeys",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_keys,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/RotateKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="RotateKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.rotate_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/SetBaseKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetBaseKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.set_base_key,
                ),
                "/policy.kasregistry.KeyAccessServerRegistryService/GetBaseKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBaseKey",
                        service_name="policy.kasregistry.KeyAccessServerRegistryService",
                        input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
                        output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_base_key,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/policy.kasregistry.KeyAccessServerRegistryService"


class KeyAccessServerRegistryServiceClientSync(ConnectClientSync):
    def list_key_access_servers(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeyAccessServers",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServersResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def get_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_key_access_server(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteKeyAccessServer",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.DeleteKeyAccessServerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_key_access_server_grants(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeyAccessServerGrants",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeyAccessServerGrantsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    def create_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.CreateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_keys(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListKeys",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.ListKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.UpdateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def rotate_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RotateKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.RotateKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def set_base_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetBaseKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.SetBaseKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_base_key(
        self,
        request: policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBaseKey",
                service_name="policy.kasregistry.KeyAccessServerRegistryService",
                input=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyRequest,
                output=policy_dot_kasregistry_dot_key__access__server__registry__pb2.GetBaseKeyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
