---
name: Ubuntu build

on: [push]

jobs:
  call-lint:
    uses: ./.github/workflows/lint-on-ubuntu.yaml

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        go-version: [1.24.x]
        python3_version: [ "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -timeout 40s -run ^TestHello$ gotdf_python -count=1 # go test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python3_version }}

      # FIXME: Add more caching
      - name: Configure gopy / dependencies, and build wheel
        run: |
          ./build-scripts/ci-build.sh

      - uses: actions/cache/restore@v4
        with:
          path: dist/otdf_python-0.2.16-py3-none-any.whl
          key: ${{ runner.os }}${{ matrix.python3_version }}-data-${{ github.sha }}

      - uses: actions/cache/save@v4
        with:
          path: dist/otdf_python-0.2.16-py3-none-any.whl
          key: ${{ runner.os }}${{ matrix.python3_version }}-data-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.python3_version }}-data-

  integration-test:
    strategy:
      fail-fast: true
      matrix:
        python3_version: [ "3.11", "3.12" ]
    needs: build
    uses: ./.github/workflows/platform-integration-test.yaml
    with:
      wheel: dist/otdf_python-0.2.16-py3-none-any.whl
      python_version: ${{ matrix.python3_version }}
