---
name: Ubuntu -- Build Python wheel using golang's gopy

on: [push]

jobs:
    call-lint:
      uses: ./.github/workflows/lint-on-ubuntu.yaml

    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        strategy:
            fail-fast: true
            matrix:
                go-version: [1.22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ matrix.go-version }}
                  cache-dependency-path: go.sum
            - name: Install dependencies
              run: go get .
            - name: Test with Go
              run: go test -timeout 40s -run ^TestHello$ gotdf_python -count=1 # go test

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            # FIXME: Add more caching
            - name: Configure gopy / dependencies, and build wheel
              run: |
                ./ci-build.sh

            - uses: actions/cache/restore@v4
              with:
                path: dist/otdf_python-0.1.10-py3-none-any.whl
                key: ${{ runner.os }}-data-${{ github.sha }}

            - uses: actions/cache/save@v4
              with:
                path: dist/otdf_python-0.1.10-py3-none-any.whl
                key: ${{ runner.os }}-data-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-data-

    integration-test:
      needs: build
      uses: ./.github/workflows/platform-integration-test.yaml
      with:
        wheel: dist/otdf_python-0.1.10-py3-none-any.whl
