---
name: Ubuntu -- Lint

on:
    workflow_call:

jobs:

  lint-ubuntu:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: true
        matrix:
            go-version: [1.22.x]
            # go-version: [ '1.19', '1.20', '1.22.x' ]

    steps:
        - uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
                go-version: ${{ matrix.go-version }}
                cache-dependency-path: go.sum
        - name: Install dependencies
          run: go get .

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - name: Install pre-commit dependencies
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        - uses: pre-commit/action@v3.0.1
