name: TestPyPIBuild

on:
  push:
    branches:
      - develop
      - chore/rewrite-in-python
  workflow_dispatch:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Build package
        run: |
          uv build

      - name: Test import
        run: |
          uv run python -c 'import otdf_python; print("Package imported successfully")'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: ./dist/*

#   build_windows:
#     if: false  # not working
#     name: Windows 310,311 x86_64
#     runs-on: windows-2019

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup project files
#         run: |
#            rm -rf poetry.lock pyproject.toml
#            cp setup_ci.py setup.py

#       - name: set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: "1.24.x"

#       - name: install gopy
#         run: go install github.com/go-python/gopy@v0.4.10

#       - name: install goimports
#         run: go install golang.org/x/tools/cmd/goimports@latest

#       - name: Build wheels
#         uses: pypa/cibuildwheel@v2.21.3
#         env:
#           # CGO_ENABLED: 1
#           CIBW_BUILD: "cp3*"
#           CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* cp313-* *-musllinux_x86_64"
#           CIBW_ARCHS: "native"
#           CIBW_ENVIRONMENT: >
#             GOARCH=amd64

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: wheels-windows-amd64
#           path: ./wheelhouse/*.whl


  release:
    permissions:
      contents: write
      # This permission is mandatory for PyPI's trusted publishing
      id-token: write
    needs: [build]
    runs-on: ubuntu-22.04
    # If branch is 'develop'
    if: github.ref == 'refs/heads/develop'

    steps:
        - uses: actions/checkout@v4
        - uses: actions/download-artifact@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"

        - name: Collect all artifacts
          run: |
            # List downloaded artifacts
            ls -la
            # Move artifacts to dist directory
            mkdir -p dist
            find . -name "*.whl" -o -name "*.tar.gz" | head -10
            cp python-package/* dist/ || echo "No artifacts found in python-package"
            ls -la dist/

        - name: Store version
          run: |
              uv add --dev hatchling
              PROJECT_VERSION=$(uv run python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
              echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

        # Publish with "trusted publisher" mechanism:
        # https://docs.pypi.org/trusted-publishers/
        #
        # Requires GHA token permission (above in YAML) and PyPI management:
        #   https://test.pypi.org/manage/project/otdf-python/settings/publishing/
        - name: Publish package distributions to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/
            packages-dir: dist/

        - uses: ncipollo/release-action@v1
          with:
            artifacts: |
                README.md,
                dist/*.whl
            body: otdf_python version ${{ env.PROJECT_VERSION }}
            makeLatest: "false"
            tag: "${{ env.PROJECT_VERSION }}-dev-${{ github.sha }}"
            # tag: v${{ env.PROJECT_VERSION }}
