name: TestPyPIBuild

on:
  push:
    branches:
      - develop
      - chore/update-docs-and-release-process
  repository_dispatch:
    types: [alpha-release-created, stable-release-created]
  workflow_dispatch:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Build package
        run: |
          uv build

      - name: Test import
        run: |
          uv run python -c 'import otdf_python; print("Package imported successfully")'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: ./dist/*


  release:
    permissions:
      contents: write
      # This permission is mandatory for PyPI's trusted publishing
      id-token: write
    needs: [build]
    runs-on: ubuntu-22.04
    # If branch is 'develop' or triggered by repository dispatch
    if: github.ref == 'refs/heads/develop' || github.event_name == 'repository_dispatch'

    steps:
        - uses: actions/checkout@v4
        - uses: actions/download-artifact@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"

        - name: Collect all artifacts
          run: |
            # List downloaded artifacts
            ls -la
            # Move artifacts to dist directory
            mkdir -p dist
            find . -name "*.whl" -o -name "*.tar.gz" | head -10
            cp python-package/* dist/ || echo "No artifacts found in python-package"
            ls -la dist/

        - name: Store version
          run: |
              PROJECT_VERSION=$(uv version --short)
              echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

        # Publish with "trusted publisher" mechanism:
        # https://docs.pypi.org/trusted-publishers/
        #
        # Requires GHA token permission (above in YAML) and PyPI management:
        #   https://test.pypi.org/manage/project/otdf-python/settings/publishing/
        - name: Publish package distributions to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/
            packages-dir: dist/

        - uses: ncipollo/release-action@v1
          with:
            artifacts: |
                README.md,
                dist/*.whl
            body: otdf_python version ${{ env.PROJECT_VERSION }}
            makeLatest: "false"
            tag: "${{ env.PROJECT_VERSION }}-dev-${{ github.sha }}"
            # tag: v${{ env.PROJECT_VERSION }}
